// App-own items (spec 06a). Not validated: every screen that shows them carries APP_QUESTION_LABEL (LOG-003).
import type { Anatomy } from '../../domain/types';

export const APP_QUESTION_LABEL = 'App question, not validated';
export const ITEM_SET_VERSION = 1;

export const SESSION_LOG = {
  feelQuestion: 'How did your squeezes feel today?',
  feelOptions: [
    { value: 1, label: 'Very weak' },
    { value: 2, label: 'Weak' },
    { value: 3, label: 'OK' },
    { value: 4, label: 'Strong' },
    { value: 5, label: 'Very strong' },
  ],
  painQuestion: 'Any pain or discomfort during or after the session?',
  painOptions: [
    { value: 'no', label: 'No' },
    { value: 'a_little', label: 'A little' },
    { value: 'yes', label: 'Yes' },
  ],
  offToggle: 'Anything felt off?',
  offQuestion: 'Tick anything that happened today.',
  offOptions: [
    { value: 'held_breath', label: 'Held my breath' },
    { value: 'pushed_down', label: 'Pushed down instead of lifting' },
    { value: 'buttocks_thighs', label: 'Squeezed my buttocks or thighs' },
    { value: 'upper_belly', label: 'Tightened my belly above the belly button' },
    { value: 'could_not_release', label: 'Could not fully let go' },
    { value: 'leak_during_exercise', label: 'Leaked a little during the exercise' },
  ],
  habitQuestion: 'Did you use the knack or after-peeing squeeze today?',
  saved: 'Saved',
  learnLink: 'Some ticks suggest a check of your technique. Do you want to do a quick check?',
} as const;

export const SELF_CHECK = {
  title: 'Monthly self-check',
  intro: 'This check has six short steps and takes about 5 minutes. The app compares your numbers only with your own past results.',
  conditionsTitle: 'Before you start',
  conditions: {
    bladder: 'Did you empty your bladder recently?',
    notAfterSession: 'Was your last training session at least an hour ago?',
    samePosition: 'Are you on your back, knees bent (the same position as last time)?',
    samePositionStanding: 'Are you standing, the same as last time?',
  },
  proceedAnyway: 'You can still continue. We will add a note to the result.',
  rest: 'Rest',
  signTitle: 'Step 1 of 6: Sign check',
  sign: {
    male: 'Squeeze once and watch in a mirror, or rest your fingertips on the skin behind your scrotum. Did the base of your penis pull back slightly and your scrotum lift (or did you feel a lift under your fingers)?',
    female: 'Did your back passage and the entrance to your vagina lift up and inwards?',
    other_unspecified: 'Squeeze once and watch in a mirror, or rest your fingertips on the skin between your genitals and back passage. Did you see or feel a lift in and up?',
  } as Record<Anatomy, string>,
  signOptions: [
    { value: 'yes', label: 'Yes, clearly' },
    { value: 'unsure', label: 'Not sure' },
    { value: 'no', label: 'No' },
  ],
  signMethod: 'How did you check?',
  signMethods: [
    { value: 'mirror', label: 'Mirror' },
    { value: 'touch', label: 'Fingertips' },
  ],
  bulge: 'Did anything bulge or push outward?',
  bulgeOptions: [
    { value: 'no', label: 'No' },
    { value: 'unsure', label: 'Not sure' },
    { value: 'yes', label: 'Yes' },
  ],
  longestTitle: 'Step 2 of 6: Longest strong hold',
  longest: 'Squeeze as strongly as you can and hold. Keep breathing. Tap Stop the moment the squeeze clearly weakens.',
  longestCap: 'That is the maximum for this check. Let go.',
  longestRetry: 'Do you want to try that step once more?',
  start: 'Start',
  stop: 'Stop',
  repeatedTitle: 'Step 3 of 6: Repeated strong holds',
  repeated: 'Tap Faded when a hold clearly weakens or you cannot finish it.',
  faded: 'Faded',
  quickTitle: 'Step 4 of 6: Quick squeezes',
  quick: 'Tap Slowed when the squeezes blur or get slower, or when you cannot let go between them.',
  slowed: 'Slowed',
  techniqueTitle: 'Step 5 of 6: Technique and relax check',
  technique: [
    { key: 'breathing_ok', text: 'Did you keep breathing normally?' },
    { key: 'glutes_belly_relaxed', text: 'Did your buttocks and belly (above the belly button) stay relaxed?' },
    { key: 'full_release', text: 'Could you feel the muscles fully let go after each squeeze?' },
  ],
  techniqueOptions: [
    { value: 'yes', label: 'Yes' },
    { value: 'unsure', label: 'Not sure' },
    { value: 'no', label: 'No' },
  ],
  painTitle: 'Step 6 of 6: Pain',
  pain: 'Any pain during or after this check?',
  painOptions: [
    { value: 'no', label: 'No' },
    { value: 'a_little', label: 'A little' },
    { value: 'yes', label: 'Yes' },
  ],
  resultTitle: 'Your record',
  longestResult: 'Longest strong hold',
  repeatedResult: 'Strong holds in a row',
  quickResult: 'Quick squeezes',
  last: 'last time',
  best: 'best',
  techniqueLink: 'Some answers suggest a check of your technique. Do you want to do Learn the squeeze again?',
  standingNext: 'Your plan now includes standing. Rest for 2 minutes. Then do the same check again, standing.',
  stopEarly: 'Stop here',
} as const;

export const EVENTS = {
  title: 'Log something',
  leakType: 'Leak or dribble',
  sexType: 'Sexual activity',
  contextType: 'Add a note about a day',
  when: 'When did it happen?',
  whenSex: 'When was this?',
  now: 'Now',
  situation: 'What were you doing?',
  situations: [
    { value: 'cough_sneeze', label: 'Coughing, sneezing or laughing', profiles: ['male', 'female', 'other_unspecified'] },
    { value: 'lifting', label: 'Lifting or exercise', profiles: ['male', 'female', 'other_unspecified'] },
    { value: 'urge', label: 'A sudden urge to go', profiles: ['male', 'female', 'other_unspecified'] },
    { value: 'after_urinating', label: 'After peeing (dribble)', profiles: ['male'] },
    { value: 'other', label: 'Other', profiles: ['male', 'female', 'other_unspecified'] },
  ],
  amount: 'How much?',
  amounts: [
    { value: 'drops', label: 'A few drops' },
    { value: 'more', label: 'More than a few drops' },
  ],
  activity: 'What kind of activity?',
  activities: [
    { value: 'penetrative_vaginal', label: 'Sex with penetration (vaginal)' },
    { value: 'other_partnered', label: 'Other partnered sex' },
    { value: 'solo', label: 'Solo' },
  ],
  firmness: 'At its firmest, how firm was your erection?',
  firmnessOptions: [
    { value: 0, label: 'Soft, no change' },
    { value: 1, label: 'A little fuller, still soft' },
    { value: 2, label: 'Partly firm' },
    { value: 3, label: 'Firm, but not fully' },
    { value: 4, label: 'Fully firm' },
    { value: null, label: 'Not sure' },
  ],
  time: 'Roughly how long from when penetration (or the main stimulation) started until you ejaculated? Your best guess is fine.',
  timeOptions: [
    { value: 'lt1', label: 'Under 1 minute' },
    { value: '1to2', label: '1 to 2 minutes' },
    { value: '2to3', label: '2 to 3 minutes' },
    { value: '3to5', label: '3 to 5 minutes' },
    { value: '5to10', label: '5 to 10 minutes' },
    { value: '10to20', label: '10 to 20 minutes' },
    { value: '20to30', label: '20 to 30 minutes' },
    { value: 'gt30', label: 'More than 30 minutes' },
    { value: 'no_ejaculation', label: 'Did not ejaculate' },
    { value: 'not_sure', label: 'Not sure' },
  ],
  typeNumber: 'Type a number',
  minutes: 'minutes',
  confirm30: 'Just checking: more than 30 minutes?',
  control: 'How much control did you feel over when you ejaculated?',
  controlEnds: ['No control at all', 'Complete control'],
  bother: 'How much did the timing bother you this time?',
  botherEnds: ['Not at all', 'Very much'],
  saved: 'Saved',
  contextKinds: [
    { value: 'illness', label: 'Ill' },
    { value: 'alcohol', label: 'Drank alcohol' },
    { value: 'new_medication', label: 'New or changed medicine' },
    { value: 'tired_stressed', label: 'Very tired or stressed' },
    { value: 'other', label: 'Other' },
  ],
  contextNote: 'Note (optional, 60 characters)',
  sexualActivityFlag: 'Any sexual activity in the past 4 weeks?',
  sexualActivityOptions: [
    { value: 'yes', label: 'Yes' },
    { value: 'no', label: 'No' },
    { value: 'prefer_not', label: 'Prefer not to say' },
  ],
} as const;
