// General UI copy (spec 05: calm, plain, UK English, no guilt, no claims; STE and voice rules in research/ux-writing/style-guide.md). Screens read copy from here.

export const APP_NAME = 'Diamond Crusher';
export const APP_TAGLINE = 'Pelvic floor training and tracking.';
export const DISCLAIMER_VERSION = 1;
export const DISCLAIMER =
  "Diamond Crusher is a training aid. It guides and tracks pelvic floor exercises as part of a healthy lifestyle. It does not diagnose any condition, and it is not medical advice or a replacement for care from a health professional. If you have pain, leaks, erection problems or any symptom that worries you, see a doctor or a pelvic health physiotherapist. In an emergency, contact emergency services. The app's own questions are not validated tests.";

export const COMMON = {
  continue: 'Continue',
  back: 'Back',
  next: 'Next',
  done: 'Done',
  save: 'Save',
  cancel: 'Cancel',
  skip: 'Skip',
  yes: 'Yes',
  no: 'No',
  close: 'Close',
  notNow: 'Not now',
  edit: 'Edit',
  delete: 'Delete',
  skipQuestion: 'Skip this question',
  finishLater: 'Save for later',
  loading: 'One moment…',
  tryAgain: 'Try again',
};

/** Messages when something fails (DS-E13): what happened, and what to do. */
export const ERRORS = {
  loadFailed: 'This page did not load. Try again. Your records are safe.',
  saveFailed: 'This was not saved. Try again.',
};

/** Words that only screen readers hear. */
export const A11Y = {
  warning: 'Warning',
  error: 'Error',
  less: 'Less',
  more: 'More',
};

export const ONBOARDING = {
  welcomeTitle: 'Welcome',
  welcomeValue: 'Short daily sessions that train your pelvic floor, step by step.',
  welcomeBody: 'Pelvic floor training and tracking that stays on this phone. No account. Nothing leaves the phone unless you export it.',
  welcomeTime: 'Setup takes about 3 minutes.',
  stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
  disclaimerTitle: 'Before you start',
  start: 'Start',
  importBackup: 'Import a backup',
  understand: 'I understand',
  adultQuestion: 'Are you 18 or older?',
  notAdult: 'This app is for adults only. A doctor or a pelvic health physiotherapist can give you advice.',
  anatomyQuestion: 'Which body is this plan for?',
  anatomyOptions: [
    { value: 'male', label: 'Male' },
    { value: 'female', label: 'Female' },
    { value: 'other_unspecified', label: 'Other or prefer not to say' },
  ],
  anatomyNote: 'Your answer sets the right guidance and checks. The exercises stay the same.',
  goalsQuestion: 'What do you want to train for?',
  goalsNote: 'Choose at least one. You can change these later.',
  ageQuestion: 'Your age (optional)',
  ageNote: 'The app uses this only to set how many days a week you train after week 12.',
  ageOptions: [
    { value: '18_29', label: '18 to 29' },
    { value: '30_44', label: '30 to 44' },
    { value: '45_59', label: '45 to 59' },
    { value: '60_74', label: '60 to 74' },
    { value: '75_plus', label: '75 or over' },
    { value: null, label: 'Prefer not to say' },
  ],
  screeningTitle: 'A few safety questions',
  finishTitle: 'All set',
  finishNext: 'Your home screen shows what to do next. Start with Learn the squeeze. It takes about 5 minutes, lying down.',
  finishBlocked: 'Your home screen shows what happens next.',
  lockTitle: 'Lock the app?',
  lockBody: 'The app can ask for your fingerprint, face or phone PIN each time it opens. The lock is off by default. You can change this in Settings at any time.',
  lockOn: 'Use the lock',
  lockOff: 'Skip the lock',
  lockUnavailable: 'This phone has no screen lock, so the app lock is not available. After you add a screen lock, you can use the app lock from Settings.',
  lockWarning: 'If you add a new fingerprint or face later, the lock may stop working. Keep a backup file so that you do not lose your data.',
};

/** Guided flows (Learn the squeeze, self-check): leaving part way (UX audit H8). */
export const FLOW = {
  leaveTitle: 'Leave?',
  leaveBody: 'This step is not saved.',
  leave: 'Leave',
};

export const PLAN = {
  title: 'When will you train?',
  intro: 'Link each session to something you already do each day. The habit is then easier to keep.',
  sessionsPerDay: 'Sessions a day',
  anchorLabel: 'After…',
  anchors: [
    { key: 'wake', label: 'When I wake' },
    { key: 'teeth', label: 'After I brush my teeth' },
    { key: 'commute', label: 'On my commute' },
    { key: 'lunch', label: 'At lunch' },
    { key: 'tv', label: 'During evening TV' },
    { key: 'bed', label: 'In bed before sleep' },
    { key: 'custom', label: 'Custom' },
  ],
  customPlaceholder: 'Your own moment (40 characters or fewer)',
  time: 'Reminder time',
  days: 'Days',
  // H9: the real session length changes with the level, so the plan does not promise a number of minutes.
  planLine: (anchor: string, _minutes?: number) => `${anchor.charAt(0).toUpperCase()}${anchor.slice(1)}, I will do my session (a few minutes).`,
  permissionWhy: 'Reminders need permission to show notifications. You can change this at any time.',
  allowReminders: 'Allow reminders',
  noReminders: 'Skip reminders',
  testTitle: 'Test your reminders',
  testBody: 'The test reminder arrives 10 seconds after you tap.',
  sendTest: 'Send a test',
  testQuestion: 'Did you see it?',
  testFixTitle: 'If reminders do not show',
  testFix: [
    'Allow notifications for Diamond Crusher in your phone settings.',
    'Remove the app from battery optimisation. Samsung and some other phones can stop reminders and not tell you.',
    'Apps in a locked private space cannot show reminders.',
  ],
  openSettings: 'Open phone settings',
  mayBeLate: 'Android may deliver reminders up to about an hour late.',
  reviewOffer: 'Reminders can lose their pull after a few weeks. Do you want to review your plan or the reminder text?',
  reviewPlan: 'Review my plan',
  remindersOff: 'Reminders are off',
  customTextWarning: 'This text can show on your lock screen, where other people can read it.',
  daysShort: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  daysLong: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  sessionLabel: (n: number) => `Session ${n}`,
  /** A slot added for a 4th or later session has no daily moment yet. */
  noAnchor: 'Pick a daily moment for this session.',
  reminderOn: 'Remind me',
  timeLine: (time: string) => `Reminder at ${time}`,
  change: 'Change',
  changeLabel: (n: number) => `Change session ${n}`,
  hour: 'Hour',
  minutes: 'Minutes',
  hourEarlier: '1 hour earlier',
  hourLater: '1 hour later',
  minutesEarlier: '5 minutes earlier',
  minutesLater: '5 minutes later',
  nextReminder: (time: string) => `Next reminder ${time}`,
  // Web only (UX audit M11): a browser can show reminders only while the app is open.
  webTitle: 'Reminders on a Mac',
  webBody: 'On a Mac, reminders show only while Diamond Crusher is open in Safari or in the Dock. If you close the tab, no reminder comes.',
  phoneTitle: 'Set reminders on your phone',
  phoneBody: 'Your phone can remind you when the app is closed. On your phone, open Diamond Crusher, then go to Settings and Reminders.',
};

export const HOME = {
  morePrompts: (n: number) => (n === 1 ? 'Show 1 more' : `Show ${n} more`),
  greeting: (name: string | null) => (name ? `Hello, ${name}` : 'Hello'),
  todayTitle: 'Today',
  sessionOf: (n: number, total: number) => `Session ${n} of ${total}`,
  startSession: 'Start session',
  learnFirst: 'Learn the squeeze',
  relaxPractice: 'Relax practice',
  weekTitle: 'This week',
  weekCount: (done: number, target: number) => `${done} of ${target} days`,
  /** Day letters for the week dots, Monday first (ISO weekday − 1). */
  dayLetters: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  dayNames: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  todayMark: 'today',
  dayTrained: 'trained',
  dayNotTrained: 'no training',
  weekNice: (target: number) => `${target} of ${target}. Nice week.`,
  paused: 'Paused',
  somethingChanged: 'Something changed?',
  somethingChangedHint: 'New pain, leaks or surgery? Update your answers.',
  logSomething: 'Log something',
  level: (n: number, name: string | null, max?: number | null) => `Level ${n}${max ? ` of ${max}` : ''}${name ? `: ${name}` : ''}`,
  next: (what: string) => `Next: ${what}`,
  nextAfter: (what: string, weeks: number) => `Next: ${what}, after ${weeks} more good ${weeks === 1 ? 'week' : 'weeks'}`,
  goodWeek: (sessions: number) => `A good week is 5 days with ${sessions} full ${sessions === 1 ? 'session' : 'sessions'} or more, and no pain.`,
  nextReminder: (when: string) => `Next reminder: ${when}`,
  whenToday: (time: string) => `today at ${time}`,
  whenTomorrow: (time: string) => `tomorrow at ${time}`,
  whenDay: (day: string, time: string) => `${day} at ${time}`,
  sessionContents: 'Today’s session',
  // W2 (Adrian, 2026-10-03): one line wherever the next check shows. "Opens" is the first day, "due" the scheduled day.
  checkLine: (first: boolean, opens: string, due: string) => `${first ? 'First check' : 'Next check'}: opens ${opens}, due ${due}`,
  checkReady: 'Your monthly check is ready',
  reviewReady: 'Your 12-week review is ready',
  shortScreenDue: 'A quick safety re-check is due',
  baselineOffer: 'Do your starting self-check',
  techniqueCheck: 'Quick technique check',
  exportReminder: 'Save a backup file. If this device loses its data, the file brings your record back.',
  saveBackup: 'Save a backup',
  firstStep: 'Your first step',
  upNext: 'Up next',
  summaryReady: 'Your weekly summary is ready',
  learnHint: 'Start here: learn the squeeze. It takes about 5 minutes.',
  blocked: 'Exercises are paused',
  everyday: 'Everyday squeezes',
  knackCard: 'New today: the knack and everyday squeezes',
  // Round 2 Today (2026-10-03, D5, A1 to A3).
  monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  /** "Saturday 3 October" */
  dateLine: (weekday: string, day: number, month: string) => `${weekday} ${day} ${month}`,
  headDone: 'Today’s plan is done',
  headRelax: 'Relax practice today',
  hero: { label: 'Your progress', path: 'Path', rings: 'Rings' },
  levelOf: (n: number, max: number | null) => (max ? `Level ${n} of ${max}` : `Level ${n}`),
  levelWord: 'Level',
  holdName: (s: number) => `${s} s holds`,
  stations: { lying: 'Lying', sitting: 'Sitting', standing: 'Standing', steady: 'Steady', longer: 'Longer' } as Record<string, string>,
  goodWeeks: (done: number, total: number) => `${done} of ${total} good ${total === 1 ? 'week' : 'weeks'}`,
  pathSpoken: (level: string, name: string, station: string, next: string) => `${level}: ${name}. You are at the ${station} stage. ${next}.`,
  pathTop: 'You are at the top of the path.',
  daysThisWeek: (n: number, target: number) => `${n} of ${target} days this week`,
  sessionsToday: (n: number, total: number) => `${n} of ${total} ${total === 1 ? 'session' : 'sessions'} today`,
  ringsSpoken: (days: string, today: string | null, level: string) => `${days}.${today ? ` ${today}.` : ''} ${level}.`,
  best: {
    hold: 'Best hold',
    inRow: 'Strong holds in a row',
    holdValue: (s: number) => `${s} s`,
    riseHold: (s: number) => `↑ ${s} s more than your first check`,
    riseInRow: (n: number) => `↑ ${n} more than your first check`,
    empty: 'Your best results show here after your first monthly check.',
    chartHold: (values: string) => `Best hold at each monthly check, in seconds: ${values}`,
    chartInRow: (values: string) => `Strong holds in a row at each monthly check: ${values}`,
  },
  todayLabel: 'Today',
  remindersLink: 'Reminders',
  slotTitle: (n: number, total: number, position: string) => `Session ${n} of ${total} · ${position}`,
  slotState: { done: 'Done', next: 'Next', later: 'Later' },
  nowLine: (time: string) => `Now, ${time}`,
  parts: { relax: 'Relax', holds: 'Holds', flicks: 'Quick squeezes', steady: 'Steady holds' },
  shapeSpoken: (holds: number, flicks: number, steady: number) =>
    `Session shape: relax, ${holds} holds, ${flicks} quick squeezes${steady ? `, ${steady} steady holds` : ''}, then relax.`,
  /** Mac hover on a day of the week (Q3): "Wed 7 Oct: 2 of 3 sessions". */
  dayHover: (date: string, n: number, total: number) => `${date}: ${n} of ${total} ${total === 1 ? 'session' : 'sessions'}`,
  daySpoken: (day: string, n: number, total: number, today: boolean) => `${day}${today ? ', today' : ''}: ${n} of ${total} ${total === 1 ? 'session' : 'sessions'}`,
  healthNote: {
    title: 'Worth getting checked',
    gotIt: 'Got it',
    willBook: 'I will book a check',
    alreadySeen: 'Already seen someone',
    returns: 'This note shows again if your answers or logged results change.',
    row: (n: number) => (n === 1 ? '1 health note' : `${n} health notes`),
  },
  suggest: {
    safety: { title: 'A quick safety re-check is due', body: 'A few short questions about your health since the last check.', action: 'Start re-check' },
    check: { title: 'Your monthly check is ready', body: 'A self-check and a few questions. It shows how your training is going.', action: 'Open check' },
    review: { title: 'Your 12-week review is ready', body: 'Look back at 12 weeks of training, then choose what comes next.', action: 'Open review' },
    technique: { title: 'Quick technique check', body: 'A short check that your squeeze is still correct.', action: 'Check technique' },
    baseline: { title: 'Do your starting self-check', body: 'It gives you a starting point, so you can see your progress later.', action: 'Start self-check' },
    summary: { title: 'Your weekly summary is ready', body: 'See how last week went.', action: 'Read summary' },
    backup: { title: 'Save a backup', body: 'If this device loses its data, the file brings your record back.', action: 'Save a backup' },
  } as Record<string, { title: string; body: string; action: string }>,
  moreTips: 'More tips',
  allArticles: 'All articles',
  levelUp: {
    title: (name: string) => `New level: ${name}`,
    body: 'Your good weeks of training made this step. Your next session uses it.',
    ok: 'Got it',
  },
  heroSync: 'Use the same Today card on all devices',
  heroSyncHint: 'Path or Rings. Off: each device keeps its own choice.',
};

/** C2: setup that onboarding no longer asks for, offered on Today after the first full session. */
export const SETUP = {
  plan: { title: 'Pick your training times', body: 'Link each session to something you do each day. The app can then remind you.', action: 'Choose times' },
  expect: { title: 'What to expect', body: 'Read how long changes usually take, and what is normal on the way.', action: 'Read it' },
  lock: { title: 'Lock the app', body: 'The app can ask for your fingerprint, face or phone PIN each time it opens.', action: 'Open settings' },
};

export const NEXT_NAME: Record<string, string> = {
  sitting: 'sitting sessions',
  standing: 'standing sessions',
  endurance: 'steady holds',
  more_standing: 'more standing sessions',
  longer_holds: 'longer holds',
  top: 'keep it steady',
};

export const LEVEL_NAME: Record<string, (after: unknown) => string> = {
  position: (a) => (a === 1 ? 'sitting unlocked' : a === 2 ? 'standing unlocked' : 'more standing'),
  endurance: () => 'steady holds added',
  hold_s: (a) => `${a} s holds`,
  hold_reps: (a) => `${a} holds a session`,
  endurance_hold_s: (a) => `${a} s steady holds`,
};

export const WELCOME_BACK = {
  title: 'Welcome back',
  body: 'Welcome back. The app starts a little easier, then builds again.',
  easier: 'Restart easier',
  pickUp: 'Continue my plan',
  reviewPlan: 'Do you want to review your reminders?',
};

export const MAINTENANCE = {
  offerTitle: 'Build phase done',
  offerBody: 'That is 12 weeks of training. From now on, a lighter routine keeps what you built. Your monthly check shows how it holds. Or you can build for 4 more weeks.',
  switch: 'Start lighter routine',
  keepBuilding: 'Add 4 weeks',
  targetChanged: (n: number) => `Your weekly target is now ${n} days, to match the lighter routine. You can change it in Settings.`,
  holdingSteady: 'Holding steady',
  topUpTitle: 'A 4-week top-up',
  topUpBody: 'Your record was lower on your last two checks. A 4-week top-up of daily sessions can help it grow again.',
  topUpAccept: 'Start the top-up',
  topUpDecline: 'Not now',
  daysToCheck: (n: number) => (n <= 0 ? 'Your monthly check is due' : `${n} days to your monthly check`),
  topOfProgramme: 'Top of the programme. From here, steady is the goal.',
};

export const EXPECTATION = 'Most changes take 6 to 12 weeks. A squeeze before you cough and after you pee can help from today.';

export const MILESTONES: Record<string, string> = {
  first_week: 'First week of training done.',
  first_target_week: 'First full week at your target. Nice.',
  first_standing: 'First standing session done.',
  pr: 'New personal best in your self-check.',
  level: 'You reached a new level.',
  build_done: '12-week build done. That is a real habit.',
};

export const PROGRESS = {
  title: 'Progress',
  // Kept from v1 (PFB-017 tile 1 now lives in Other records).
  overviewSymptoms: 'Questionnaire answers',
  noChange: 'No change',
  somethingChanged: 'Something changed',
  noCheckYet: 'No check-up yet',
  trainingWeek: 'Training this week',
  yourRecord: 'Your record',
  trend: { improvement: 'Up', steady: 'Steady', decline: 'Down', too_early: 'Too early to tell' } as Record<string, string>,
  trendSpoken: (v: string) => `Your record: ${v}.`,

  // Range tabs inside each card (round 2 P1, P4; PFB-018).
  range: { all: 'All', '12w': '12 weeks', '12m': '12 months' } as Record<string, string>,
  rangeSpoken: { all: 'since you started', '12w': 'last 12 weeks', '12m': 'last 12 months' } as Record<string, string>,
  rangeLabel: (card: string) => `Time range for ${card}`,

  // Training consistency (hero card, PFB-010).
  consistency: 'Training consistency',
  thisWeek: 'This week',
  weekCount: (n: number, target: number) => `${n} of ${target} days`,
  weekDaysSpoken: (n: number, target: number) => `This week: ${n} of ${target} days trained.`,
  weeksOnTarget: (on: number, of: number) => `Weeks on target: ${on} of the last ${of}`,
  weeksOnTargetFirst: 'Weeks on target show after your first full week.',
  captionWeeks: 'Days trained each week. Dashed line: your target. Tick: on target. Dashed outline: this week so far.',
  captionMonths: 'Average days trained a week, by month. Dashed line: your target. Tick: on target.',
  consistencyEmptyTitle: 'Your chart starts after 2 weeks',
  consistencyEmpty: 'Each day you train adds to it. Until then, this week shows at the top.',
  summaries: 'Weekly summaries',
  summariesLast: (range: string, n: number, target: number) => `Last: ${range}, ${n} of ${target} days`,
  summariesNone: 'Your first summary comes after your first full week.',

  // How your squeezes feel (PFB-014, PFB-024, LOG-025) and milestones (MOT-032).
  feel: 'How your squeezes feel',
  feelSub: 'The usual value (median) of how your squeezes felt over 4 weeks.',
  feelUsually: (word: string) => `Usually ${word}`,
  feelCompare: {
    higher: 'Higher than the 8 weeks before.',
    lower: 'Lower than the 8 weeks before.',
    same: 'About the same as the 8 weeks before.',
  } as Record<string, string>,
  feelBeforeWas: (word: string) => `In the 8 weeks before, it was usually ${word}.`,
  feelFrom: (n: number) => `From ${n} logged sessions in the last 4 weeks.`,
  feelProgress: (n: number, min: number) => `${n} of ${min} sessions logged`,
  feelProgressBody: 'After a session, log how your squeezes felt. The usual value shows when 6 sessions in 4 weeks have a log.',
  feelNow: 'Last 4 weeks',
  feelBefore: '8 weeks before',
  feelScaleSpoken: (now: string, before: string | null) =>
    `Scale from Very weak to Very strong. Last 4 weeks: ${now}.${before ? ` The 8 weeks before: ${before}.` : ''}`,
  feelByWeek: 'Usual value by week',
  feelByWeekShow: 'Show by week',
  feelByWeekHide: 'Hide by week',
  milestones: 'Milestones',
  milestonesNone: 'New personal bests, new levels and your first full week show here.',
  showAll: 'Show all',
  milestone: {
    pr: (what: string) => `New best: ${what}`,
    prGeneric: 'New personal best in your self-check',
    level: (name: string) => `New level: ${name}`,
    ceiling: (name: string) => `Plan matched to your check: ${name}`,
    restart: (name: string) => `Restarted easier: ${name}`,
    first_week: 'First week of training done',
    first_target_week: 'First full week at your target',
    first_standing: 'First standing session done',
    build_done: '12-week build done',
  },
  bestWhat: {
    longest_hold: (v: number) => `${v} s longest strong hold`,
    repeated_holds: (v: number) => `${v} strong holds in a row`,
    quick_flicks: (v: number) => `${v} quick squeezes`,
  } as Record<string, (v: number) => string>,

  // Your record (one card, PFB-011, PFB-020, HE-03).
  recordSub: 'From your monthly self-check. It compares you only with your own past results.',
  positionLabel: 'Position',
  measureLabel: 'Measure to chart',
  lying: 'Lying',
  standing: 'Standing',
  tiles: {
    longest_hold: 'Longest strong hold',
    repeated_holds: 'Strong holds in a row',
    quick_flicks: 'Quick squeezes',
  } as Record<string, string>,
  best: (v: string) => `Best ${v}`,
  tileSpoken: (name: string, latest: string, best: string) => `${name}: latest ${latest}, best ${best}.`,
  recordNoneTitle: 'No self-check yet',
  recordNone: 'Your record starts with your first self-check. It compares you only with your own past results.',
  recordLegend: 'Star: your best. Open dot: a check condition was missing, or you were not sure of your technique. The line stops where there was no check.',
  holdLengthNote: 'The line also stops where the hold length of the check changed.',
  noCheck: 'no check',

  // Sexual activity items (PFB-016, PFB-024).
  sexual: 'Sexual activity items',
  sexualSub: 'Usual values (median) over 4 weeks. Each value needs 3 entries in 4 weeks.',
  sexualItems: { hardness: 'Firmness', control_0_10: 'Control', bother_0_10: 'Bother' } as Record<string, string>,
  outOf: (max: number) => `of ${max}`,
  sexualCompare: {
    higher: 'Higher than the 8 weeks before',
    lower: 'Lower than the 8 weeks before',
    same: 'About the same as the 8 weeks before',
  } as Record<string, string>,
  sexualNotEnough: 'Needs 3 entries in 4 weeks',
  lowerIsBetter: 'Lower is better',

  // Time to ejaculation by activity type (PFB-016, EVT-031, Q3). No norms and no labels for a time.
  ejac: 'Time to ejaculation',
  ejacSub: 'Your usual time range (median) over 4 weeks, for each kind of activity. Each needs 3 entries in 4 weeks.',
  ejacFrom: (n: number) => `From ${n} ${n === 1 ? 'entry' : 'entries'} in the last 4 weeks`,
  ejacNone: 'When you log a time with a sexual activity, it shows here.',
  ejacTable: 'Usual time range per 4 weeks',
  ejacSpoken: (activity: string, range: string, sub: string) => `${activity}: ${range}. ${sub}.`,

  // Other records (tertiary list) and their details (PFB-012, PFB-013, PFB-015, PFB-017).
  otherRecords: 'Other records',
  leaks: 'Logged leaks',
  leaksRow: (n: number) => `${n} in the last 12 weeks`,
  leaksSub: 'Leaks you logged. Logging is optional, so this may not show every leak.',
  leaksBlocks: 'Leaks per 4 weeks, by situation.',
  leaksEmptyTitle: 'No leaks logged',
  leaksEmpty: 'If you log a leak, it shows here. Logging is optional.',
  questionnaires: 'Questionnaire answers',
  symptomRow: { none: 'No check-up yet', changed: 'Something changed' } as Record<string, string>,
  symptomNoChange: (date: string) => `No change, last on ${date}`,
  scoreTitle: (name: string) => `${name} score`,
  scoreLowerFewer: 'A lower score means fewer symptoms.',
  scoreHigherBetter: 'A higher score is better.',
  scoreBand: 'Shaded band: a change inside it is smaller than a meaningful change.',
  scoreNone: 'These answers have no score to chart. They show in the list below.',
  checkUp: 'check-up',
  checkUpExplain:
    'Your answers are at the "no problem" end and that is good news. The app will continue to ask, so that you see any change early. Your progress shows in your training record and monthly self-check instead.',

  // Tables and chart controls (PFB-006, chart accessibility review items 2 and 9).
  table: 'Show as table',
  chart: 'Show as chart',
  col: {
    week: 'Week of',
    month: 'Month',
    date: 'Date',
    days: 'Days trained',
    avg: 'Days a week',
    hold: 'Hold (s)',
    row: 'In a row',
    quick: 'Quick',
    value: 'Value',
    note: 'Note',
    weeks: 'Weeks',
    leaks: 'Leaks',
    situations: 'By situation',
    questionnaire: 'Questionnaire',
    score: 'Score',
    entries: 'Entries',
    sessions: 'Sessions',
  },
  note: {
    onTarget: 'On target',
    soFar: 'So far',
    notStarted: 'Before you started',
    condition: 'A check condition was missing',
    technique: 'Not sure of technique',
    noCheck: 'No check',
    best: 'Your best',
    notEnough: 'Not enough entries',
  },
  situationCount: (n: number, what: string) => `${n} ${what}`,

  // Chart summaries for screen readers (review item 1) and point labels (hover and keyboard on the web).
  spoken: {
    weeks: (range: string, target: number, now: number, on: number, of: number) =>
      `Days trained each week, ${range}. Target ${target} days. This week ${now} days so far. ${on} of ${of} full weeks on target.`,
    months: (range: string, target: number, now: string, on: number) =>
      `Average days trained a week by month, ${range}. Target ${target} days. This month ${now} so far. ${on} months on target.`,
    line: (title: string, range: string, n: number, latest: string, best: string) =>
      `${title}, ${range}. ${n} values. Latest ${latest}. Best ${best}.`,
    leaks: (n: number, blocks: number) => `Logged leaks per 4 weeks, last ${blocks} blocks. ${n} leaks in all.`,
    score: (name: string, n: number, latest: string) => `${name} score. ${n} results. Latest ${latest}.`,
    none: 'No values yet.',
    noValue: 'no value',
    chartKeys: 'Use the left and right arrow keys to move between values.',
  },
  point: (date: string, value: string, note: string | null) => `${date}: ${value}${note ? `. ${note}` : ''}`,
  dayNote: 'Day note',
  markerLegend: 'Small triangle under the chart: a day note.',

  // Mac detail panel (decision M3).
  panelTitle: 'Details',
  panelEmpty: 'Select a card, a bar or a row to see its details here.',
  noData: 'Nothing to show yet.',
};

export const MESSAGES = {
  'PFB-030': 'Early weeks are mostly about learning the movement. Most people need 6 to 12 weeks before their record changes.',
  'PFB-031': (measure: string, from: number, to: number) =>
    `Your ${measure} went up on your last two checks: ${from} → ${to}. Your training shows in your record.`,
  'PFB-031-pb': 'New personal best. Your training shows in your record.',
  'PFB-033':
    'Your record stayed steady. That is common after the first few months. You can continue as you are (steady is a result too), try a more difficult position or longer holds, or re-check your technique.',
  'PFB-034': 'Your record is steady. More regular training is the most likely way to move it. Do you want to change your reminders or weekly target?',
  'PFB-035': (measure: string, notes: string) =>
    `Your ${measure} was lower on your last two checks. This can happen with illness, tiredness or a busy month.${notes ? ` Notes in that time: ${notes}.` : ''} Check the notes on your chart. Then think about a technique refresher.`,
  'PFB-037': (weeks: number) =>
    `After ${weeks} weeks of training, your symptoms look about the same. It is a good idea to have a pelvic health physiotherapist or doctor check things and your technique.`,
  'PFB-045': 'If timing bothers you, a doctor can discuss the options with you.',
  neutral: 'A new week starts now.',
};

export const MEASURE_NAME: Record<string, string> = {
  longest_hold: 'longest strong hold',
  repeated_holds: 'strong holds in a row',
  quick_flicks: 'quick squeezes',
};

export const SUMMARY = {
  title: 'Your week',
  firstNote: 'Your first summary appears after your first full week.',
  range: (a: string, b: string) => `${a} to ${b}`,
  days: (d: number, t: number) => `${d} of ${t} days.`,
  belowTarget: (d: number, t: number) => `${d} of ${t} days. A new week starts now.`,
  sessions: (c: number, p: number) => `${c} of ${p} sessions.`,
  pain: 'You noted discomfort this week, so your plan stays the same for now.',
  progressionSessions:
    'Weekly target done. Your plan goes to the next level after a week with at least 2 full sessions on 5 days. For now, it stays the same.',
  progressionOther: 'Weekly target done. Your plan stays the same this week. That is normal.',
  logged: (leaks: number, sex: number) =>
    `Logged: ${[leaks ? `${leaks} leak${leaks === 1 ? '' : 's'}` : '', sex ? `${sex} sexual activit${sex === 1 ? 'y' : 'ies'}` : ''].filter(Boolean).join(', ')}`,
  next: (d: string) => `Next check: ${d}`,
  // PFB-050: the Summaries history.
  history: 'Past summaries',
  historyRow: (n: number, target: number) => `${n} of ${target} days`,
  historyNone: 'Past summaries show here after your second full week.',
};

export const BUNDLE = {
  monthlyTitle: 'Monthly check',
  quarterlyTitle: '12-week review',
  expected: (min: number) => `About ${min} minutes. You can do each part at a different time.`,
  parts: {
    safety: 'Safety re-check',
    sexual_flag: 'Sexual activity',
    questionnaires: 'Questions',
    self_check: 'Self-check',
  } as Record<string, string>,
  partDone: 'Done',
  startPart: 'Start',
  allDone: 'Check done. See you next time.',
  exportOffer: 'Save a backup file now?',
  notYet: 'This check opens 3 days before it is due.',
  aboutMinutes: (min: number) => `About ${min} minutes.`,
  opensOn: (date: string) => `Opens ${date}`,
  lockedPart: (part: string, date: string) => `${part}. Opens ${date}.`,
  noneYet: 'No check is planned yet. The first check comes 4 weeks after you start training.',
  skip: 'Skip this check',
  skipAsk: 'Skip this check?',
  skipAskBody: 'The parts you did are kept. The parts you did not do stay empty until the next check.',
  startPartFor: (part: string) => `Start: ${part}`,
  selfCheckTitle: 'Self-check at any time',
  selfCheckBody: 'Do a self-check when you want to see where you are. It does not replace the monthly check.',
  selfCheckNow: 'Start self-check',
  historyTitle: 'Past checks',
  historyEmpty: 'No past checks yet.',
  historyStatus: { completed: 'Done', skipped: 'Skipped', missed: 'Not done' } as Record<string, string>,
  seeResults: 'See results',
  recallHeader: (t: string) => t,
  consistencyNote: 'You logged leaks in the last 4 weeks. Does your answer look right?',
  keep: 'Keep my answers',
  review: 'Review answers',
  rushed: 'Answered quickly',
  resultScore: (name: string, x: number, y: number) => `Your score on ${name}: ${x} of ${y}`,
  unavailable: 'This questionnaire is not available now',
  validatedLabel: (name: string) => `Validated questionnaire: ${name}`,
  noValidated: 'The app adds validated questionnaires when their licences are in place. Until then, the check uses the self-check and the app’s own questions.',
};

export const SETTINGS = {
  title: 'Settings',
  profile: 'Profile',
  nickname: 'Nickname (optional)',
  anatomy: 'Body',
  anatomyChangeNote: 'If you change this, the app asks all the safety questions again.',
  goals: 'Goals',
  ageBand: 'Age range',
  training: 'Training',
  sessionsPerDay: 'Sessions a day',
  weeklyTarget: 'Weekly target (days)',
  maintenanceTarget: 'Weekly target after 12 weeks',
  weekStart: 'Week starts on',
  sound: 'Sound',
  soundOptions: [
    { value: 'off', label: 'Off' },
    { value: 'tones', label: 'Tones' },
    { value: 'voice', label: 'Voice' },
  ],
  vibration: 'Vibration',
  tryCues: 'Try sound and vibration',
  // Round 2 (2026-10-03): no upper limit. Above 3 a day, one line says that trials did not test it (B1.3, B4.3).
  sessionsUntested: 'Trials used 2 or 3 sessions a day. More than 3 has not been tested. Stop a session when the squeeze gets weak.',
  sessionsTested: 'Trials used 2 or 3 sessions a day.',
  // ENG-031: 1 a day in maintenance, so the number cannot change there.
  sessionsMaintenance: '1 a day while you keep your results.',
  // Reminders keep in step with sessions a day, with Undo (round 2 decision, REM-001).
  remindersUpdated: (added: readonly string[], off: readonly string[]) => {
    const list = (t: readonly string[]) => (Array.isArray(t) ? (t.length > 1 ? `${t.slice(0, -1).join(', ')} and ${t[t.length - 1]}` : t[0] ?? '') : '');
    const parts = [list(added) ? `added ${list(added)}` : '', list(off) ? `turned off ${list(off)}` : ''].filter(Boolean);
    return parts.length ? `Reminders updated: ${parts.join(', ')}.` : 'Reminders updated.';
  },
  remindersDiffer: (n: number) => `Your reminders: ${n} a day. They did not change.`,
  remindersAreOff: 'Reminders are off.',
  remindersPausedUntil: (d: string) => `Reminders are paused until ${d}.`,
  remindersPaused: 'Reminders are paused.',
  remindersMacOnly: 'On this Mac, reminders show only while the app is open.',
  undo: 'Undo',
  undoKey: 'or press ⌘Z',
  editTimes: 'Edit times',
  turnOn: 'Turn on',
  weekDays: [
    { value: 1, label: 'Monday' },
    { value: 7, label: 'Sunday' },
  ],
  textSize: 'Text size',
  textSizeOptions: [
    { value: 1, label: 'Normal' },
    { value: 1.15, label: 'Large' },
    { value: 1.3, label: 'Larger' },
    { value: 1.5, label: 'Largest' },
  ],
  textSizeNote: 'This Mac only. The page loads again to use the new size.',
  theme: 'Theme',
  themeOptions: [
    { value: 'system', label: 'Phone setting' },
    { value: 'light', label: 'Light' },
    { value: 'dark', label: 'Dark' },
  ],
  functionalCues: 'Everyday squeeze tips on the home screen',
  reminders: 'Reminders',
  lockScreen: 'On the lock screen',
  lockScreenOptions: [
    { value: 'private', label: 'Show "Reminder" only' },
    { value: 'secret', label: 'Hide completely' },
  ],
  pause: 'Pause reminders',
  pauseOptions: [
    { days: 1, label: '1 day' },
    { days: 7, label: '1 week' },
    { days: 14, label: '2 weeks' },
    { days: 28, label: '4 weeks' },
    { days: 0, label: 'Until I start them again' },
  ],
  resume: 'Restart reminders',
  pausedUntil: (d: string) => `Paused until ${d}`,
  pausedIndef: 'Paused',
  knack: 'Daily knack nudge',
  weeklySummaryNote: 'Weekly summary reminder',
  anchorDay: 'Monthly check day',
  security: 'Privacy and security',
  lock: 'App lock',
  lockTimeout: 'Lock again after',
  lockTimeoutOptions: [
    { value: 0, label: 'Immediately' },
    { value: 60, label: '1 minute' },
    { value: 300, label: '5 minutes' },
    { value: 900, label: '15 minutes' },
  ],
  data: 'Backup and data',
  checkIns: 'Check-ins',
  sync: 'Sync',
  about: 'About',
  learn: 'Library',
  relearn: 'Repeat Learn the squeeze',
  somethingChanged: 'Something changed?',
  version: (v: string) => `Version ${v}`,
};

export const DATA = {
  title: 'Backup and data',
  whatTitle: 'What the app keeps',
  what:
    'Your profile, goals, safety answers, training sessions, logs, self-checks, questionnaire answers, events and settings. Nothing else.',
  whereTitle: 'Where it is',
  where: 'The app keeps your data only on this phone, in an encrypted database. The phone’s secure storage holds the key.',
  leavesTitle: 'What leaves the phone',
  leaves: 'Nothing, unless you export a backup file or sync by code with your other device. The app has no internet permission, no account, no ads and no tracking.',
  backupsTitle: 'Phone backups',
  backups: 'Your phone’s cloud and transfer backups do not include the app. Use a backup file to move to a new phone.',
  lastBackup: (d: string | null) => (d ? `Last backup: ${d}` : 'Backup file'),
  noBackupWarn: 'No backup file yet. If you lose this phone, you lose your records.',
  staleWarn: (days: number) => `Your last backup is ${days} days old. Save a new backup file.`,
  storageTitle: 'Browser storage',
  storageKept: 'Protected. The browser does not delete this data to make space. It still deletes it if you clear website data.',
  storageNotKept: 'Not protected. The browser can delete this data if the Mac is low on space, or if you do not use the app for some time.',
  storageUnknown: 'This browser does not say if it keeps this data. Save a backup file often.',
  export: 'Save a backup',
  import: 'Import a backup',
  deleteAll: 'Delete all my data',
  exportTitle: 'Save a backup file',
  exportBody: 'Choose a passphrase. You need it to open the file. If you lose it, there is no way to recover it.',
  passphrase: 'Passphrase',
  passphraseAgain: 'Type it again',
  passphraseRule: 'At least 12 characters, or 4 words.',
  passphraseMismatch: 'The two passphrases are different. Type them again.',
  strength: { too_short: 'Too short', ok: 'OK', strong: 'Strong' } as Record<string, string>,
  working: 'The app now encrypts your file. This can take up to 1 minute.',
  exportDone: 'Backup saved. Keep the file and your passphrase safe.',
  savedAsk: 'Did the file save in a safe place?',
  savedAskNote: 'The app counts the backup only when you say yes. If you closed the share window, choose No.',
  savedYes: 'Yes, it saved',
  savedNo: 'No',
  savedNotYet: 'The backup is not counted. Tap Save a backup again, then choose a place for the file.',
  chooseAnother: 'Choose another file',
  thisDevice: (s: number, c: number, q: number, e: number) => `On this device now: ${s} sessions, ${c} self-checks, ${q} questionnaires, ${e} events`,
  newerHere: (d: string) => `This device has records after the last day in the file (${d}). Replace deletes them. Merge keeps them.`,
  replaceAsk: 'Replace everything?',
  replaceAskBody: 'All records on this device are deleted and the records in the file take their place. You cannot undo this.',
  errors: {
    not_a_backup: 'This file is not a Diamond Crusher backup. Choose the file that ends in .dcbk.',
    unsupported_version: 'A newer version of the app made this file. Install the newer version, then import the file.',
    invalid_content: 'The file is damaged. Nothing changed. Try another backup file.',
    other: 'Something went wrong. Nothing changed. Try again.',
  } as Record<string, string>,
  importTitle: 'Import a backup file',
  importBody: 'Choose the backup file. Then type its passphrase.',
  pickFile: 'Choose file',
  unlockFile: 'Open file',
  previewTitle: 'What is in the file',
  previewLine: (s: number, c: number, q: number, e: number) => `${s} sessions, ${c} self-checks, ${q} questionnaires, ${e} events`,
  range: (a: string, b: string) => `From ${a} to ${b}`,
  replace: 'Replace',
  replaceNote: 'The file replaces everything on this phone.',
  merge: 'Merge',
  mergeNote: 'The app keeps the records from both. Choose which profile and settings to keep:',
  keepPhone: 'This phone',
  keepBackup: 'The backup',
  importDone: 'Import done. Your records are all here.',
  wrongPassphrase: 'The passphrase is wrong, or the file is damaged. Nothing changed. Type the passphrase again.',
  deleteTitle: 'Delete all my data',
  deleteBody: 'This erases all app data on this phone and cancels all reminders. You cannot undo this.',
  deleteNote: 'This does not delete backup files that you saved in other places, or the data on a paired phone or Mac.',
  deleteType: 'Type DELETE to continue',
  deleteWord: 'DELETE',
  deleteButton: 'Delete everything',
  updateNote: 'Save a backup file before you install an update.',
};

export const LOCK = {
  title: 'Diamond Crusher is locked',
  unlock: 'Unlock',
  erase: 'Erase and restart',
  eraseWarning: 'This erases all data in the app. Without a backup file, you cannot recover it.',
};

export const UNREADABLE = {
  title: 'The app cannot open your data',
  body: 'The app cannot read the data on this phone. This can happen after a move to a new phone or a security change.',
  import: 'Import a backup',
  fresh: 'Erase and restart',
  confirm: 'This erases the unreadable data. Continue?',
  newer: 'A newer version of the app made this data. Install the newer version.',
  tryFirst: 'First, try again. A short problem (for example, a second browser tab) can also stop the app. Erase only if Try again does not work.',
  importHint: 'To import a backup file, start fresh first. The first screen then offers "Import a backup".',
};

export const ABOUT = {
  title: 'About',
  description: APP_TAGLINE,
  licences: 'Questionnaires: the app’s own questions are not validated. The app adds validated questionnaires only with permission from the licence holder.',
  evidence: 'About the evidence',
  // Decision 8 (2026-09-29): the intended purpose, so the app stays a training aid (EU MDR / UK MHRA boundary).
  purposeTitle: 'What this app is for',
  purpose: [
    'Diamond Crusher guides pelvic floor exercises for adults. It keeps a private record of your training and your answers.',
    'It does not diagnose any condition or follow a condition over time. It does not replace care from a health professional.',
  ],
};

/** Desktop layout (Mac): sidebar, toolbar and keyboard shortcuts. */
export const DESKTOP = {
  nav: {
    home: 'Today',
    progress: 'Progress',
    log: 'Log',
    check: 'Check-ins',
    library: 'Library',
    reminders: 'Reminders',
    settings: 'Settings',
    data: 'Backup and data',
  },
  navGroups: { train: 'Train', track: 'Track', app: 'App' },
  /** Short names under the icons of the narrow rail (768 to 1039 wide, or a collapsed sidebar). */
  navShort: {
    home: 'Today',
    progress: 'Progress',
    log: 'Log',
    check: 'Check-ins',
    library: 'Library',
    reminders: 'Reminders',
    settings: 'Settings',
    data: 'Backup',
  },
  collapse: 'Hide sidebar',
  expand: 'Show sidebar',
  quickLog: 'Log something',
  /** Phone tab bar: the same names as the sidebar, plus More (Settings and the other sections). */
  tabs: 'Sections',
  keyHint: (key: number) => `Press ${key}`,
  lastBackup: (days: number | null) =>
    days == null ? 'Last backup: never' : days === 0 ? 'Last backup: today' : days === 1 ? 'Last backup: yesterday' : `Last backup: ${days} days ago`,
  start: 'Start session',
  todayDone: 'Done for today',
  back: 'Back',
  close: 'Close',
  theme: 'Appearance',
  themeShort: { system: 'Auto', light: 'Light', dark: 'Dark' } as Record<string, string>,
  shortcutsHint: 'Press ? for keyboard shortcuts',
  shortcutsTitle: 'Keyboard shortcuts',
  shortcuts: [
    { keys: 'S', what: 'Start today’s session' },
    { keys: 'L', what: 'Log a leak, sexual activity or a note' },
    { keys: '1 to 8', what: 'Go to a section in the sidebar' },
    { keys: '⌘ \\', what: 'Hide or show the sidebar' },
    { keys: 'T', what: 'Switch light, dark or automatic appearance' },
    { keys: 'Space', what: 'Pause or resume a running session' },
    { keys: 'V', what: 'In a session, switch between the ring and the wave' },
    { keys: 'Esc', what: 'Go back or close this panel. In a session, pause, then end.' },
    { keys: '?', what: 'Show these shortcuts' },
  ],
  sessionKeys: 'Space pauses · Esc twice ends',
  flowKeys: 'Space or Enter continues',
  tapKeys: 'Space or Enter taps the big button',
  shortcutsToggle: 'Use single-key shortcuts',
  shortcutsToggleHint: 'If you use speech input or other assistive tools, set this to off.',
  startKey: 'or press S',
  articles: 'Articles',
  settingsNotes: {
    profile: 'Used to choose your exercises and wording. It stays on this device.',
    training: 'How often you train, and how sessions sound and feel.',
    appearance: 'Light, dark, or match the device. Both themes are easy to read.',
    security: 'Who can open the app, and your data.',
    more: 'Learning, re-checks and version details.',
  },
  helpAndChanges: 'Help and changes',
  more: 'More',
  sessionProgress: (pct: number) => `${pct}% of this session done`,
  // Session timer views (T1, M2): ring and wave, switched with a control, the dots or V.
  sessionKeysView: 'Space pauses · Esc twice ends · V switches the view',
  sessionView: 'Timer view',
  sessionViewRing: 'Ring',
  sessionViewWave: 'Wave',
  sessionRingAlt: (left: number, pct: number) => `Timer ring. ${left} seconds left in this step. ${pct}% of this session done.`,
  sessionWaveAlt: (left: number, pct: number) =>
    `Timer wave. Up is squeeze and the line at the bottom is let go. ${left} seconds left in this step. ${pct}% of this session done.`,
};
