#!/usr/bin/env node
// Generates src/ui/polaris.ts from Shopify's Polaris design tokens (@shopify/polaris-tokens).
// React Native can't read CSS variables, so the tokens the app uses are copied in as plain numbers and hex colours.
// Run `node scripts/polaris-tokens.js` after updating the package; `--check` fails if the file is out of date.
const fs = require('fs');
const path = require('path');
const { themes } = require('@shopify/polaris-tokens');

const OUT = path.join(__dirname, '..', 'src', 'ui', 'polaris.ts');

const COLORS = [
  'color-bg',
  'color-bg-surface',
  'color-bg-surface-secondary',
  'color-bg-surface-selected',
  'color-bg-surface-active',
  'color-bg-surface-hover',
  'color-bg-surface-info',
  'color-bg-surface-success',
  'color-bg-surface-warning',
  'color-bg-surface-caution',
  'color-bg-surface-critical',
  'color-bg-fill-brand',
  'color-bg-fill-brand-hover',
  'color-bg-fill-brand-disabled',
  'color-bg-fill-secondary',
  'color-bg-fill-tertiary',
  'color-bg-fill-critical',
  'color-bg-fill-success',
  'color-bg-fill-emphasis',
  'color-bg-fill-info',
  'color-text',
  'color-text-secondary',
  'color-text-disabled',
  'color-text-brand-on-bg-fill',
  'color-text-link',
  'color-text-info',
  'color-text-success',
  'color-text-warning',
  'color-text-caution',
  'color-text-critical',
  'color-border',
  'color-border-secondary',
  'color-border-emphasis',
  'color-border-focus',
  'color-input-bg-surface',
  'color-input-border',
  'color-icon-secondary',
  'color-nav-bg',
  'color-nav-bg-surface-hover',
  'color-nav-bg-surface-selected',
];

function hex(rgba) {
  if (rgba.startsWith('#')) return rgba.toUpperCase();
  const m = rgba.match(/rgba?\(([^)]+)\)/);
  if (!m) throw new Error(`Unexpected colour ${rgba}`);
  const [r, g, b, a = '1'] = m[1].split(',').map((s) => s.trim());
  const h = (n) => Number(n).toString(16).padStart(2, '0').toUpperCase();
  const alpha = Number(a);
  return `#${h(r)}${h(g)}${h(b)}${alpha < 1 ? h(Math.round(alpha * 255)) : ''}`;
}

const px = (rem) => Math.round(parseFloat(rem) * 16 * 100) / 100;

function colours(theme) {
  return Object.fromEntries(COLORS.map((k) => [k.replace(/^color-/, ''), hex(themes[theme].color[k])]));
}

function pick(group, prefix) {
  const t = themes['light-mobile'][group];
  return Object.fromEntries(
    Object.entries(t)
      .filter(([k]) => k.startsWith(prefix))
      .map(([k, v]) => [k.slice(prefix.length), px(v)]),
  );
}

const text = themes['light-mobile'].text;
const variants = ['heading-2xl', 'heading-xl', 'heading-lg', 'heading-md', 'heading-sm', 'body-lg', 'body-md', 'body-sm'];
const typography = Object.fromEntries(
  variants.map((v) => [
    v,
    {
      fontSize: px(text[`text-${v}-font-size`]),
      lineHeight: px(text[`text-${v}-font-line-height`]),
      fontWeight: Number(text[`text-${v}-font-weight`]),
      letterSpacing: px(text[`text-${v}-font-letter-spacing`]),
    },
  ]),
);

// Motion: durations in ms and the easing curves, for hover, page and celebration animations.
const m = themes['light-mobile'].motion;
const motion = {
  duration: Object.fromEntries(['100', '150', '200', '300', '500'].map((d) => [d, parseInt(m[`motion-duration-${d}`], 10)])),
  ease: m['motion-ease'],
  easeOut: m['motion-ease-out'],
  easeInOut: m['motion-ease-in-out'],
};
const breakpoints = Object.fromEntries(Object.entries(themes['light-mobile'].breakpoints).map(([k, v]) => [k.replace('breakpoints-', ''), px(v)]));

const tokens = {
  light: colours('light-mobile'),
  dark: colours('dark-experimental'),
  space: pick('space', 'space-'),
  radius: pick('border', 'border-radius-'),
  typography,
  motion,
  breakpoints,
};

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'node_modules', '@shopify', 'polaris-tokens', 'package.json'), 'utf8'));
const body = `// Generated by scripts/polaris-tokens.js from @shopify/polaris-tokens ${pkg.version}. Do not edit by hand.
// Themes: light-mobile (light) and dark-experimental (dark). Sizes are in px (1rem = 16px).
export const polaris = ${JSON.stringify(tokens, null, 2)} as const;
`;

if (require.main !== module) {
  // Required by the test: only compute the file body.
} else if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== body) {
    console.error('src/ui/polaris.ts is out of date. Run: node scripts/polaris-tokens.js');
    process.exit(1);
  }
} else {
  fs.writeFileSync(OUT, body);
  console.log(`Wrote ${path.relative(process.cwd(), OUT)}`);
}

module.exports = { body };
